// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djwndfmoksmqrejombqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqd25kZm1va3NtcXJlam9tYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDI4MzAsImV4cCI6MjA2NzU3ODgzMH0.jyMVZk9mzqyZXySp-VS14QwMGarOYlqX4NOxItCTvpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});